### ISSUE TITLE
Redesign Website

### ISSUE THREAD

**Issue by Jake0oo0** [Jake0oo0/crafatar#51]
The site is very cluttered right now, could definitely use a cleanup/redesign.

**Comment by Tama63** [comment]
Had a quick crack at this.

https://github.com/Tama63/crafatar with a demo over on https://pacific-depths-7149.herokuapp.com/ (avatars are broken due to missing redis?).

Let me know what you think.

**Comment by jomo** [comment]
That's great. I like the table idea, although I find the table style a bit ugly and don't like the `#F9F9F9` color.
"blazing fast" sounds good, too.

Want to make a PR?

**Comment by Jake0oo0** [comment]
Feel free to come talk about it in #spongy if you can hop on iRC.
