### ISSUE TITLE
Replace existsSync with exists

### ISSUE THREAD

**Issue by Jake0oo0** [Jake0oo0/crafatar#58]
existsSync is potentially slowing Crafatar down unnecessarily, and replacing it with the async function wouldn't be a bad idea.

**Comment by jomo** [comment]
Not sure if it has an actual impact since they are only called inside async functions, but sync is definitely not the JS way :stuck_out_tongue_winking_eye:

**Comment by connor4312** [comment]
> Not sure if it has an actual impact since they are only called inside async functions, but sync is definitely not the JS way

Sync calls anywhere block the _entire_ stack. There's an good talk from ScotlandJS that should give you a better idea of the Node.js event loop http://2014.jsconf.eu/speakers/philip-roberts-what-the-heck-is-the-event-loop-anyway.html

**Comment by jomo** [comment]
Interesting talk, ty
