### ISSUE TITLE
Request IDs

### ISSUE THREAD

**Issue by jomo** [Jake0oo0/crafatar#77]
At the moment we pass the ID (uuid / name) to pretty much every method and prefix our logs with it.
This starts to cause trouble when we have multiple requests for the same ID in short time as you can't differ between them.

Instead of prefixing the ID, we should generate a random request ID that is passed to all the methods and prefixes the logs. The ID would only be logged once at the beginning.

**Comment by Jake0oo0** [comment]
Should we pass this ID into the response header so we know what request it was based on the header ID?

**Comment by jomo** [comment]
great idea

**Comment by jomo** [comment]
The `X-Request-ID` header will be used to display the req ID.
